/**
 * Pre-populated Niche Database
 *
 * Contains 50+ pre-analyzed YouTube niches with competition levels,
 * monetization potential, and growth trends based on 2025-2026 data.
 */

import type { NicheData } from './types/niche';

export const NICHE_DATABASE: NicheData[] = [
  // TECHNOLOGY
  {
    id: 'tech-ai-tools',
    name: 'AI Tools & Tutorials',
    category: 'technology',
    description: 'Reviews, tutorials, and comparisons of AI tools like ChatGPT, Midjourney, and other emerging AI technologies.',
    competitionLevel: 'medium',
    monetizationPotential: 9,
    averageCPM: 18.50,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Matt Wolfe', url: 'https://youtube.com/@maboroshi', subscribers: '850K' },
      { name: 'All About AI', url: 'https://youtube.com/@AllAboutAI', subscribers: '620K' },
      { name: 'Skill Leap AI', url: 'https://youtube.com/@SkillLeapAI', subscribers: '410K' },
    ],
    contentTypes: ['Tutorial', 'Review', 'Comparison', 'News'],
    targetAudience: 'Professionals, creators, and tech enthusiasts aged 25-45',
    keywords: ['AI', 'ChatGPT', 'artificial intelligence', 'machine learning', 'automation'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'tech-programming',
    name: 'Programming Tutorials',
    category: 'technology',
    description: 'Coding tutorials, programming language guides, and software development tips.',
    competitionLevel: 'high',
    monetizationPotential: 8,
    averageCPM: 15.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Fireship', url: 'https://youtube.com/@Fireship', subscribers: '2.8M' },
      { name: 'Traversy Media', url: 'https://youtube.com/@TraversyMedia', subscribers: '2.2M' },
      { name: 'Web Dev Simplified', url: 'https://youtube.com/@WebDevSimplified', subscribers: '1.5M' },
    ],
    contentTypes: ['Tutorial', 'Course', 'Tips', 'Project Build'],
    targetAudience: 'Aspiring developers and junior programmers aged 18-35',
    keywords: ['programming', 'coding', 'JavaScript', 'Python', 'web development'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'tech-gadgets',
    name: 'Tech Gadget Reviews',
    category: 'technology',
    description: 'Reviews and unboxings of smartphones, laptops, headphones, and other consumer tech.',
    competitionLevel: 'high',
    monetizationPotential: 9,
    averageCPM: 22.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'MKBHD', url: 'https://youtube.com/@mkbhd', subscribers: '19M' },
      { name: 'Linus Tech Tips', url: 'https://youtube.com/@LinusTechTips', subscribers: '16M' },
      { name: 'Unbox Therapy', url: 'https://youtube.com/@UnboxTherapy', subscribers: '20M' },
    ],
    contentTypes: ['Review', 'Unboxing', 'Comparison', 'Setup Tour'],
    targetAudience: 'Tech enthusiasts and consumers aged 18-45',
    keywords: ['tech review', 'gadgets', 'smartphone', 'unboxing', 'tech'],
    requiresFace: true,
    minHoursPerWeek: 15,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'tech-cybersecurity',
    name: 'Cybersecurity Education',
    category: 'technology',
    description: 'Online security tips, ethical hacking tutorials, and privacy protection guides.',
    competitionLevel: 'low',
    monetizationPotential: 8,
    averageCPM: 20.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'NetworkChuck', url: 'https://youtube.com/@NetworkChuck', subscribers: '3.5M' },
      { name: 'John Hammond', url: 'https://youtube.com/@_JohnHammond', subscribers: '1.2M' },
      { name: 'The Cyber Mentor', url: 'https://youtube.com/@TCMSecurityAcademy', subscribers: '680K' },
    ],
    contentTypes: ['Tutorial', 'Explanation', 'Tips', 'News'],
    targetAudience: 'IT professionals and security-conscious users aged 20-40',
    keywords: ['cybersecurity', 'hacking', 'security', 'privacy', 'ethical hacking'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'tech-automation',
    name: 'No-Code & Automation',
    category: 'technology',
    description: 'Tutorials on no-code tools, workflow automation, and building apps without coding.',
    competitionLevel: 'low',
    monetizationPotential: 8,
    averageCPM: 16.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Thomas Frank Explains', url: 'https://youtube.com/@ThomasFrankExplains', subscribers: '520K' },
      { name: 'Buildcamp', url: 'https://youtube.com/@Buildcamp', subscribers: '180K' },
      { name: 'Automate Your Life', url: 'https://youtube.com/@AutomateYourLife', subscribers: '95K' },
    ],
    contentTypes: ['Tutorial', 'Template', 'Walkthrough', 'Comparison'],
    targetAudience: 'Entrepreneurs, small business owners, and productivity enthusiasts',
    keywords: ['no-code', 'automation', 'Notion', 'Zapier', 'Make', 'workflow'],
    requiresFace: false,
    minHoursPerWeek: 6,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // FINANCE
  {
    id: 'finance-personal',
    name: 'Personal Finance',
    category: 'finance',
    description: 'Budgeting tips, saving strategies, debt payoff, and financial literacy education.',
    competitionLevel: 'high',
    monetizationPotential: 9,
    averageCPM: 25.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Graham Stephan', url: 'https://youtube.com/@GrahamStephan', subscribers: '4.6M' },
      { name: 'Andrei Jikh', url: 'https://youtube.com/@AndreiJikh', subscribers: '2.2M' },
      { name: 'Nate OBrien', url: 'https://youtube.com/@NateOBrien', subscribers: '1.3M' },
    ],
    contentTypes: ['Tips', 'Education', 'Lifestyle', 'Story'],
    targetAudience: 'Young adults and families aged 22-45 looking to improve finances',
    keywords: ['personal finance', 'budgeting', 'saving money', 'debt free', 'financial freedom'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'finance-investing',
    name: 'Stock Market Investing',
    category: 'finance',
    description: 'Stock analysis, investment strategies, market news, and portfolio building.',
    competitionLevel: 'high',
    monetizationPotential: 10,
    averageCPM: 35.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Meet Kevin', url: 'https://youtube.com/@MeetKevin', subscribers: '1.9M' },
      { name: 'Financial Education', url: 'https://youtube.com/@FinancialEducation', subscribers: '980K' },
      { name: 'Joseph Carlson', url: 'https://youtube.com/@JosephCarlsonShow', subscribers: '450K' },
    ],
    contentTypes: ['Analysis', 'News', 'Education', 'Portfolio Update'],
    targetAudience: 'Investors and finance enthusiasts aged 25-55',
    keywords: ['stocks', 'investing', 'stock market', 'portfolio', 'dividends'],
    requiresFace: true,
    minHoursPerWeek: 15,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'finance-crypto',
    name: 'Cryptocurrency',
    category: 'finance',
    description: 'Crypto news, blockchain technology explanations, and investment analysis.',
    competitionLevel: 'medium',
    monetizationPotential: 8,
    averageCPM: 18.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Coin Bureau', url: 'https://youtube.com/@CoinBureau', subscribers: '2.5M' },
      { name: 'Altcoin Daily', url: 'https://youtube.com/@AltcoinDaily', subscribers: '1.4M' },
      { name: 'Benjamin Cowen', url: 'https://youtube.com/@BenjaminCowen', subscribers: '820K' },
    ],
    contentTypes: ['News', 'Analysis', 'Education', 'Prediction'],
    targetAudience: 'Crypto investors and tech-savvy individuals aged 20-40',
    keywords: ['cryptocurrency', 'Bitcoin', 'Ethereum', 'blockchain', 'DeFi'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'finance-realestate',
    name: 'Real Estate Investing',
    category: 'finance',
    description: 'Property investment strategies, market analysis, and passive income through real estate.',
    competitionLevel: 'medium',
    monetizationPotential: 10,
    averageCPM: 30.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'BiggerPockets', url: 'https://youtube.com/@BiggerPockets', subscribers: '1.2M' },
      { name: 'Ken McElroy', url: 'https://youtube.com/@KenMcElroy', subscribers: '680K' },
      { name: 'Graham Stephan Real Estate', url: 'https://youtube.com/@TheGrahamStephanShow', subscribers: '890K' },
    ],
    contentTypes: ['Education', 'Analysis', 'Tips', 'Tour'],
    targetAudience: 'Aspiring investors and homeowners aged 28-55',
    keywords: ['real estate', 'property investing', 'rental income', 'house flipping', 'passive income'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'finance-sidehustle',
    name: 'Side Hustles & Online Income',
    category: 'finance',
    description: 'Ways to make money online, side business ideas, and passive income strategies.',
    competitionLevel: 'high',
    monetizationPotential: 8,
    averageCPM: 15.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Ali Abdaal', url: 'https://youtube.com/@aliabdaal', subscribers: '5.5M' },
      { name: 'Charlie Chang', url: 'https://youtube.com/@CharlieChang', subscribers: '1.8M' },
      { name: 'Mark Tilbury', url: 'https://youtube.com/@MarkTilbury', subscribers: '3.2M' },
    ],
    contentTypes: ['Tips', 'Tutorial', 'Story', 'Review'],
    targetAudience: 'Young adults seeking additional income aged 18-35',
    keywords: ['side hustle', 'make money online', 'passive income', 'online business', 'freelance'],
    requiresFace: true,
    minHoursPerWeek: 6,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // GAMING
  {
    id: 'gaming-letsplay',
    name: 'Let\'s Play & Gaming Commentary',
    category: 'gaming',
    description: 'Gameplay videos with entertaining commentary across various games.',
    competitionLevel: 'high',
    monetizationPotential: 6,
    averageCPM: 8.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Markiplier', url: 'https://youtube.com/@markiplier', subscribers: '36M' },
      { name: 'jacksepticeye', url: 'https://youtube.com/@jacksepticeye', subscribers: '31M' },
      { name: 'DanTDM', url: 'https://youtube.com/@DanTDM', subscribers: '28M' },
    ],
    contentTypes: ['Gameplay', 'Commentary', 'Series', 'Challenge'],
    targetAudience: 'Gamers aged 13-30',
    keywords: ['gaming', 'lets play', 'gameplay', 'gaming commentary', 'walkthrough'],
    requiresFace: true,
    minHoursPerWeek: 20,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },
  {
    id: 'gaming-esports',
    name: 'Esports & Competitive Gaming',
    category: 'gaming',
    description: 'Pro gaming tips, tournament coverage, and competitive game analysis.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 10.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'theScore esports', url: 'https://youtube.com/@theaboroshi', subscribers: '2.8M' },
      { name: 'LoL Esports', url: 'https://youtube.com/@lolesports', subscribers: '5.2M' },
      { name: 'Valorant Champions Tour', url: 'https://youtube.com/@ValorantEsports', subscribers: '2.1M' },
    ],
    contentTypes: ['Analysis', 'News', 'Highlights', 'Tips'],
    targetAudience: 'Competitive gamers and esports fans aged 16-30',
    keywords: ['esports', 'pro gaming', 'competitive gaming', 'tournament', 'ranked'],
    requiresFace: false,
    minHoursPerWeek: 12,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'gaming-mobile',
    name: 'Mobile Gaming',
    category: 'gaming',
    description: 'Mobile game reviews, gameplay, and guides for iOS and Android games.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 6.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'iFerg', url: 'https://youtube.com/@iFerg', subscribers: '8.5M' },
      { name: 'HawksNest', url: 'https://youtube.com/@HawksNest', subscribers: '3.2M' },
      { name: 'Sumit007', url: 'https://youtube.com/@FLAVOR007', subscribers: '4.8M' },
    ],
    contentTypes: ['Gameplay', 'Review', 'Tips', 'News'],
    targetAudience: 'Mobile gamers aged 13-35',
    keywords: ['mobile games', 'mobile gaming', 'iOS games', 'Android games', 'PUBG Mobile'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'gaming-retro',
    name: 'Retro Gaming & Game History',
    category: 'gaming',
    description: 'Classic games, gaming history, and nostalgic content about older gaming eras.',
    competitionLevel: 'low',
    monetizationPotential: 5,
    averageCPM: 7.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Scott The Woz', url: 'https://youtube.com/@ScottTheWoz', subscribers: '1.9M' },
      { name: 'AVGN', url: 'https://youtube.com/@Cinemassacre', subscribers: '3.6M' },
      { name: 'Gaming Historian', url: 'https://youtube.com/@GamingHistorian', subscribers: '1.3M' },
    ],
    contentTypes: ['Documentary', 'Review', 'History', 'Collection'],
    targetAudience: 'Nostalgic gamers and gaming enthusiasts aged 25-45',
    keywords: ['retro gaming', 'classic games', 'gaming history', 'Nintendo', 'SEGA'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // HEALTH & FITNESS
  {
    id: 'health-workout',
    name: 'Home Workouts',
    category: 'health',
    description: 'Exercise routines, workout plans, and fitness challenges that can be done at home.',
    competitionLevel: 'high',
    monetizationPotential: 7,
    averageCPM: 12.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'THENX', url: 'https://youtube.com/@OFFICIALTHENX', subscribers: '8.5M' },
      { name: 'Blogilates', url: 'https://youtube.com/@Blogilates', subscribers: '6.8M' },
      { name: 'MadFit', url: 'https://youtube.com/@MadFit', subscribers: '10M' },
    ],
    contentTypes: ['Workout', 'Challenge', 'Routine', 'Tips'],
    targetAudience: 'Fitness beginners and home exercisers aged 18-45',
    keywords: ['home workout', 'exercise', 'fitness', 'workout routine', 'no equipment'],
    requiresFace: true,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'health-nutrition',
    name: 'Nutrition & Healthy Eating',
    category: 'health',
    description: 'Diet advice, meal prep guides, and nutritional education.',
    competitionLevel: 'medium',
    monetizationPotential: 8,
    averageCPM: 14.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Dr. Eric Berg', url: 'https://youtube.com/@DrEricBergDC', subscribers: '12M' },
      { name: 'Thomas DeLauer', url: 'https://youtube.com/@ThomasDeLauer', subscribers: '3.5M' },
      { name: 'Pick Up Limes', url: 'https://youtube.com/@PickUpLimes', subscribers: '4M' },
    ],
    contentTypes: ['Education', 'Recipe', 'Meal Prep', 'Tips'],
    targetAudience: 'Health-conscious individuals aged 25-55',
    keywords: ['nutrition', 'healthy eating', 'diet', 'meal prep', 'weight loss'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'health-mental',
    name: 'Mental Health & Wellness',
    category: 'health',
    description: 'Mental health awareness, coping strategies, and wellness tips.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 10.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Psych2Go', url: 'https://youtube.com/@Psych2Go', subscribers: '12M' },
      { name: 'Kati Morton', url: 'https://youtube.com/@KatiMorton', subscribers: '1.4M' },
      { name: 'Therapy in a Nutshell', url: 'https://youtube.com/@TherapyinaNutshell', subscribers: '1.8M' },
    ],
    contentTypes: ['Education', 'Tips', 'Story', 'Explanation'],
    targetAudience: 'Young adults seeking mental wellness aged 18-40',
    keywords: ['mental health', 'anxiety', 'depression', 'self-care', 'therapy'],
    requiresFace: false,
    minHoursPerWeek: 6,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'health-yoga',
    name: 'Yoga & Meditation',
    category: 'health',
    description: 'Yoga practices, meditation guides, and mindfulness content.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 11.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Yoga With Adriene', url: 'https://youtube.com/@yogawithadriene', subscribers: '13M' },
      { name: 'Headspace', url: 'https://youtube.com/@Headspace', subscribers: '1.8M' },
      { name: 'Boho Beautiful', url: 'https://youtube.com/@BohoBeautiful', subscribers: '2.8M' },
    ],
    contentTypes: ['Practice', 'Tutorial', 'Meditation', 'Routine'],
    targetAudience: 'Mindfulness seekers and yoga practitioners aged 25-55',
    keywords: ['yoga', 'meditation', 'mindfulness', 'stretching', 'relaxation'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // EDUCATION
  {
    id: 'edu-science',
    name: 'Science Education',
    category: 'education',
    description: 'Educational videos explaining scientific concepts, experiments, and discoveries.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 8.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Veritasium', url: 'https://youtube.com/@veritasium', subscribers: '15M' },
      { name: 'Kurzgesagt', url: 'https://youtube.com/@kurzgesagt', subscribers: '23M' },
      { name: 'SmarterEveryDay', url: 'https://youtube.com/@smartereveryday', subscribers: '11M' },
    ],
    contentTypes: ['Explanation', 'Experiment', 'Documentary', 'Animation'],
    targetAudience: 'Curious minds and students aged 14-45',
    keywords: ['science', 'physics', 'chemistry', 'biology', 'education'],
    requiresFace: false,
    minHoursPerWeek: 15,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'edu-history',
    name: 'History & Documentary',
    category: 'education',
    description: 'Historical events, biographies, and documentary-style educational content.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 9.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Oversimplified', url: 'https://youtube.com/@OverSimplified', subscribers: '9M' },
      { name: 'History Matters', url: 'https://youtube.com/@HistoryMatters', subscribers: '3.5M' },
      { name: 'Kings and Generals', url: 'https://youtube.com/@KingsandGenerals', subscribers: '3.2M' },
    ],
    contentTypes: ['Documentary', 'Animation', 'Explanation', 'Story'],
    targetAudience: 'History enthusiasts and students aged 16-55',
    keywords: ['history', 'historical events', 'biography', 'documentary', 'war history'],
    requiresFace: false,
    minHoursPerWeek: 12,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'edu-language',
    name: 'Language Learning',
    category: 'education',
    description: 'Language tutorials, pronunciation guides, and cultural education.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 10.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'SpanishPod101', url: 'https://youtube.com/@SpanishPod101', subscribers: '2.2M' },
      { name: 'JapanesePod101', url: 'https://youtube.com/@JapanesePod101', subscribers: '2.5M' },
      { name: 'Dreaming Spanish', url: 'https://youtube.com/@DreamingSpanish', subscribers: '1.4M' },
    ],
    contentTypes: ['Lesson', 'Tutorial', 'Immersion', 'Tips'],
    targetAudience: 'Language learners aged 18-50',
    keywords: ['language learning', 'Spanish', 'Japanese', 'English', 'learn language'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },
  {
    id: 'edu-math',
    name: 'Mathematics Education',
    category: 'education',
    description: 'Math tutorials, problem-solving, and mathematical concepts explained.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 8.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: '3Blue1Brown', url: 'https://youtube.com/@3blue1brown', subscribers: '6M' },
      { name: 'Numberphile', url: 'https://youtube.com/@numberphile', subscribers: '4.7M' },
      { name: 'Professor Leonard', url: 'https://youtube.com/@ProfessorLeonard', subscribers: '2.8M' },
    ],
    contentTypes: ['Tutorial', 'Explanation', 'Problem Solving', 'Animation'],
    targetAudience: 'Students and math enthusiasts aged 14-30',
    keywords: ['mathematics', 'math', 'calculus', 'algebra', 'geometry'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },

  // LIFESTYLE
  {
    id: 'lifestyle-productivity',
    name: 'Productivity & Organization',
    category: 'lifestyle',
    description: 'Time management, productivity systems, and organizational tips.',
    competitionLevel: 'medium',
    monetizationPotential: 8,
    averageCPM: 14.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Ali Abdaal', url: 'https://youtube.com/@aliabdaal', subscribers: '5.5M' },
      { name: 'Matt D\'Avella', url: 'https://youtube.com/@MattDAvella', subscribers: '3.8M' },
      { name: 'Thomas Frank', url: 'https://youtube.com/@ThomasFrank', subscribers: '3M' },
    ],
    contentTypes: ['Tips', 'System', 'Review', 'Documentary'],
    targetAudience: 'Professionals and students seeking efficiency aged 20-40',
    keywords: ['productivity', 'time management', 'organization', 'habits', 'efficiency'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'lifestyle-minimalism',
    name: 'Minimalism & Simple Living',
    category: 'lifestyle',
    description: 'Minimalist lifestyle, decluttering, and intentional living content.',
    competitionLevel: 'low',
    monetizationPotential: 6,
    averageCPM: 10.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Matt D\'Avella', url: 'https://youtube.com/@MattDAvella', subscribers: '3.8M' },
      { name: 'The Minimalists', url: 'https://youtube.com/@TheMinimalists', subscribers: '850K' },
      { name: 'Lefie', url: 'https://youtube.com/@Lefie', subscribers: '420K' },
    ],
    contentTypes: ['Documentary', 'Tips', 'Tour', 'Story'],
    targetAudience: 'People seeking simplicity aged 25-50',
    keywords: ['minimalism', 'declutter', 'simple living', 'intentional', 'less is more'],
    requiresFace: true,
    minHoursPerWeek: 6,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'lifestyle-vlog',
    name: 'Daily Vlogging',
    category: 'lifestyle',
    description: 'Day-in-the-life content, personal vlogs, and lifestyle documentation.',
    competitionLevel: 'high',
    monetizationPotential: 6,
    averageCPM: 8.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Casey Neistat', url: 'https://youtube.com/@casey', subscribers: '12M' },
      { name: 'Emma Chamberlain', url: 'https://youtube.com/@emmachamberlain', subscribers: '12M' },
      { name: 'David Dobrik', url: 'https://youtube.com/@daviddobrik', subscribers: '18M' },
    ],
    contentTypes: ['Vlog', 'Story', 'Day in Life', 'Adventure'],
    targetAudience: 'Young viewers seeking entertainment aged 13-30',
    keywords: ['vlog', 'daily vlog', 'lifestyle', 'day in my life', 'routine'],
    requiresFace: true,
    minHoursPerWeek: 15,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },

  // BUSINESS
  {
    id: 'business-entrepreneur',
    name: 'Entrepreneurship',
    category: 'business',
    description: 'Business building, startup advice, and entrepreneurial mindset content.',
    competitionLevel: 'high',
    monetizationPotential: 9,
    averageCPM: 20.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'GaryVee', url: 'https://youtube.com/@garyvee', subscribers: '4.5M' },
      { name: 'Noah Kagan', url: 'https://youtube.com/@noahkagan', subscribers: '820K' },
      { name: 'My First Million', url: 'https://youtube.com/@MyFirstMillionPod', subscribers: '580K' },
    ],
    contentTypes: ['Interview', 'Tips', 'Story', 'Analysis'],
    targetAudience: 'Aspiring entrepreneurs and business owners aged 22-45',
    keywords: ['entrepreneurship', 'startup', 'business', 'founder', 'success'],
    requiresFace: true,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'business-marketing',
    name: 'Digital Marketing',
    category: 'business',
    description: 'Marketing strategies, social media tips, and advertising education.',
    competitionLevel: 'medium',
    monetizationPotential: 9,
    averageCPM: 22.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Neil Patel', url: 'https://youtube.com/@NeilPatel', subscribers: '1.2M' },
      { name: 'Adam Erhart', url: 'https://youtube.com/@AdamErhart', subscribers: '680K' },
      { name: 'Vanessa Lau', url: 'https://youtube.com/@VanessaLau', subscribers: '850K' },
    ],
    contentTypes: ['Tutorial', 'Strategy', 'Tips', 'Analysis'],
    targetAudience: 'Marketers and business owners aged 25-50',
    keywords: ['digital marketing', 'social media marketing', 'SEO', 'advertising', 'content marketing'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'business-ecommerce',
    name: 'E-commerce & Dropshipping',
    category: 'business',
    description: 'Online store building, dropshipping guides, and e-commerce strategies.',
    competitionLevel: 'medium',
    monetizationPotential: 8,
    averageCPM: 16.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Wholesale Ted', url: 'https://youtube.com/@WholesaleTed', subscribers: '1.3M' },
      { name: 'Sebastian Ghiorghiu', url: 'https://youtube.com/@SebastianGhiorghiu', subscribers: '980K' },
      { name: 'Hayden Bowles', url: 'https://youtube.com/@HaydenBowles', subscribers: '680K' },
    ],
    contentTypes: ['Tutorial', 'Case Study', 'Strategy', 'Review'],
    targetAudience: 'Aspiring online business owners aged 18-40',
    keywords: ['ecommerce', 'dropshipping', 'Shopify', 'online store', 'Amazon FBA'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // CREATIVE
  {
    id: 'creative-photography',
    name: 'Photography',
    category: 'creative',
    description: 'Photography tutorials, camera reviews, and editing techniques.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 12.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Peter McKinnon', url: 'https://youtube.com/@PeterMcKinnon', subscribers: '6M' },
      { name: 'Mango Street', url: 'https://youtube.com/@MangoStreet', subscribers: '1.8M' },
      { name: 'COOPH', url: 'https://youtube.com/@COOPH', subscribers: '1.2M' },
    ],
    contentTypes: ['Tutorial', 'Review', 'Tips', 'Behind the Scenes'],
    targetAudience: 'Photography enthusiasts and aspiring professionals aged 18-45',
    keywords: ['photography', 'camera', 'photo editing', 'Lightroom', 'composition'],
    requiresFace: true,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },
  {
    id: 'creative-videoediting',
    name: 'Video Editing',
    category: 'creative',
    description: 'Video editing tutorials, software guides, and filmmaking techniques.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 11.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Justin Odisho', url: 'https://youtube.com/@JustinOdisho', subscribers: '1.5M' },
      { name: 'Premiere Gal', url: 'https://youtube.com/@PremiereGal', subscribers: '680K' },
      { name: 'Casey Faris', url: 'https://youtube.com/@CaseyFaris', subscribers: '850K' },
    ],
    contentTypes: ['Tutorial', 'Tips', 'Review', 'Breakdown'],
    targetAudience: 'Content creators and aspiring editors aged 16-40',
    keywords: ['video editing', 'Premiere Pro', 'DaVinci Resolve', 'After Effects', 'filmmaking'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },
  {
    id: 'creative-music',
    name: 'Music Production',
    category: 'creative',
    description: 'Music production tutorials, beat making, and mixing/mastering guides.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 9.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Andrew Huang', url: 'https://youtube.com/@andrewhuang', subscribers: '2.4M' },
      { name: 'In The Mix', url: 'https://youtube.com/@inthemix', subscribers: '1.4M' },
      { name: 'Simon Servida', url: 'https://youtube.com/@SimonServida', subscribers: '980K' },
    ],
    contentTypes: ['Tutorial', 'Beat Making', 'Review', 'Breakdown'],
    targetAudience: 'Music producers and aspiring artists aged 16-35',
    keywords: ['music production', 'beat making', 'FL Studio', 'Ableton', 'mixing'],
    requiresFace: false,
    minHoursPerWeek: 12,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'creative-art',
    name: 'Digital Art & Illustration',
    category: 'creative',
    description: 'Digital art tutorials, drawing techniques, and illustration guides.',
    competitionLevel: 'medium',
    monetizationPotential: 5,
    averageCPM: 7.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Proko', url: 'https://youtube.com/@ProkoTV', subscribers: '2.5M' },
      { name: 'Marco Bucci', url: 'https://youtube.com/@marcobucci', subscribers: '980K' },
      { name: 'Jazza', url: 'https://youtube.com/@Jazza', subscribers: '6M' },
    ],
    contentTypes: ['Tutorial', 'Speed Paint', 'Tips', 'Challenge'],
    targetAudience: 'Artists and illustration enthusiasts aged 14-40',
    keywords: ['digital art', 'drawing', 'illustration', 'Procreate', 'Photoshop'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },

  // FOOD
  {
    id: 'food-recipes',
    name: 'Recipe & Cooking Tutorials',
    category: 'food',
    description: 'Step-by-step cooking tutorials and recipe demonstrations.',
    competitionLevel: 'high',
    monetizationPotential: 7,
    averageCPM: 11.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Joshua Weissman', url: 'https://youtube.com/@JoshuaWeissman', subscribers: '10M' },
      { name: 'Binging with Babish', url: 'https://youtube.com/@babishculinaryuniverse', subscribers: '10M' },
      { name: 'Tasty', url: 'https://youtube.com/@Tasty', subscribers: '21M' },
    ],
    contentTypes: ['Recipe', 'Tutorial', 'Challenge', 'Review'],
    targetAudience: 'Home cooks and food enthusiasts aged 20-50',
    keywords: ['cooking', 'recipes', 'food', 'how to cook', 'kitchen'],
    requiresFace: true,
    minHoursPerWeek: 12,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },
  {
    id: 'food-budget',
    name: 'Budget Cooking',
    category: 'food',
    description: 'Affordable meal ideas, budget-friendly recipes, and frugal cooking tips.',
    competitionLevel: 'low',
    monetizationPotential: 6,
    averageCPM: 8.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Joshua Weissman - Budget', url: 'https://youtube.com/@JoshuaWeissman', subscribers: '10M' },
      { name: 'Struggle Meals', url: 'https://youtube.com/@StruggleMeals', subscribers: '450K' },
      { name: 'Budget Bytes', url: 'https://youtube.com/@BudgetBytes', subscribers: '180K' },
    ],
    contentTypes: ['Recipe', 'Tips', 'Meal Prep', 'Challenge'],
    targetAudience: 'Students and budget-conscious families aged 18-45',
    keywords: ['budget cooking', 'cheap meals', 'frugal', 'affordable recipes', 'save money'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'food-baking',
    name: 'Baking & Desserts',
    category: 'food',
    description: 'Baking tutorials, dessert recipes, and pastry techniques.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 9.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Preppy Kitchen', url: 'https://youtube.com/@PreppyKitchen', subscribers: '4.5M' },
      { name: 'Cupcake Jemma', url: 'https://youtube.com/@CupcakeJemma', subscribers: '2.8M' },
      { name: 'Sally\'s Baking Addiction', url: 'https://youtube.com/@SallysBakingAddiction', subscribers: '680K' },
    ],
    contentTypes: ['Recipe', 'Tutorial', 'Tips', 'Challenge'],
    targetAudience: 'Home bakers and dessert lovers aged 20-50',
    keywords: ['baking', 'desserts', 'cake', 'cookies', 'pastry'],
    requiresFace: true,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['beginner', 'intermediate', 'advanced'],
  },

  // TRAVEL
  {
    id: 'travel-adventure',
    name: 'Adventure Travel',
    category: 'travel',
    description: 'Adventure travel vlogs, extreme destinations, and outdoor exploration.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 12.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Kara and Nate', url: 'https://youtube.com/@KaraandNate', subscribers: '3.8M' },
      { name: 'Lost LeBlanc', url: 'https://youtube.com/@LostLeBlanc', subscribers: '2.2M' },
      { name: 'FunForLouis', url: 'https://youtube.com/@FunForLouis', subscribers: '2.1M' },
    ],
    contentTypes: ['Vlog', 'Documentary', 'Guide', 'Adventure'],
    targetAudience: 'Adventure seekers and travel enthusiasts aged 20-40',
    keywords: ['travel', 'adventure', 'backpacking', 'explore', 'destination'],
    requiresFace: true,
    minHoursPerWeek: 20,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'travel-budget',
    name: 'Budget Travel',
    category: 'travel',
    description: 'Budget travel tips, cheap destination guides, and money-saving travel hacks.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 10.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Gabriel Traveler', url: 'https://youtube.com/@GabrielTraveler', subscribers: '1.2M' },
      { name: 'Hey Nadine', url: 'https://youtube.com/@HeyNadine', subscribers: '780K' },
      { name: 'Wolters World', url: 'https://youtube.com/@WoltersWorld', subscribers: '1.8M' },
    ],
    contentTypes: ['Guide', 'Tips', 'Vlog', 'Review'],
    targetAudience: 'Budget travelers and backpackers aged 18-35',
    keywords: ['budget travel', 'cheap travel', 'backpacking', 'travel tips', 'save money'],
    requiresFace: true,
    minHoursPerWeek: 15,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // PETS
  {
    id: 'pets-dogs',
    name: 'Dog Training & Care',
    category: 'pets',
    description: 'Dog training tutorials, behavior tips, and pet care advice.',
    competitionLevel: 'medium',
    monetizationPotential: 7,
    averageCPM: 12.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Zak George\'s Dog Training', url: 'https://youtube.com/@zakgeorge21', subscribers: '3.8M' },
      { name: 'McCann Dog Training', url: 'https://youtube.com/@McCannDogs', subscribers: '2.4M' },
      { name: 'Simpawtico Dog Training', url: 'https://youtube.com/@Simpawtico', subscribers: '1.2M' },
    ],
    contentTypes: ['Tutorial', 'Tips', 'Review', 'Vlog'],
    targetAudience: 'Dog owners and pet parents aged 25-55',
    keywords: ['dog training', 'puppy training', 'dog behavior', 'pet care', 'dogs'],
    requiresFace: true,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'pets-cats',
    name: 'Cat Content & Care',
    category: 'pets',
    description: 'Cat behavior, care tips, and entertaining cat content.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 8.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Jackson Galaxy', url: 'https://youtube.com/@JacksonGalaxy', subscribers: '2.5M' },
      { name: 'Kitten Lady', url: 'https://youtube.com/@KittenLady', subscribers: '1.6M' },
      { name: 'The Dodo', url: 'https://youtube.com/@TheDodo', subscribers: '14M' },
    ],
    contentTypes: ['Tips', 'Entertainment', 'Education', 'Rescue'],
    targetAudience: 'Cat owners and animal lovers aged 20-50',
    keywords: ['cats', 'cat behavior', 'cat care', 'kittens', 'cat tips'],
    requiresFace: false,
    minHoursPerWeek: 6,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // DIY
  {
    id: 'diy-home',
    name: 'Home Improvement DIY',
    category: 'diy',
    description: 'DIY home projects, renovation tutorials, and home repair guides.',
    competitionLevel: 'medium',
    monetizationPotential: 8,
    averageCPM: 15.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Home RenoVision DIY', url: 'https://youtube.com/@HouseImprovements', subscribers: '2.8M' },
      { name: 'This Old House', url: 'https://youtube.com/@thisoldhouse', subscribers: '2.5M' },
      { name: 'Vancouver Carpenter', url: 'https://youtube.com/@VancouverCarpenter', subscribers: '1.8M' },
    ],
    contentTypes: ['Tutorial', 'Project', 'Tips', 'Review'],
    targetAudience: 'Homeowners and DIY enthusiasts aged 30-60',
    keywords: ['DIY', 'home improvement', 'renovation', 'home repair', 'carpentry'],
    requiresFace: true,
    minHoursPerWeek: 12,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'diy-crafts',
    name: 'Crafts & Handmade',
    category: 'diy',
    description: 'Craft tutorials, handmade projects, and creative DIY ideas.',
    competitionLevel: 'medium',
    monetizationPotential: 5,
    averageCPM: 7.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: '5-Minute Crafts', url: 'https://youtube.com/@5MinuteCraftsDIY', subscribers: '80M' },
      { name: 'Moriah Elizabeth', url: 'https://youtube.com/@moraboroshi', subscribers: '10M' },
      { name: 'HGTV Handmade', url: 'https://youtube.com/@HGTVHandmade', subscribers: '1.5M' },
    ],
    contentTypes: ['Tutorial', 'DIY', 'Challenge', 'Compilation'],
    targetAudience: 'Craft enthusiasts and hobbyists aged 15-45',
    keywords: ['crafts', 'DIY', 'handmade', 'art', 'creative'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },

  // AUTOMOTIVE
  {
    id: 'auto-reviews',
    name: 'Car Reviews',
    category: 'automotive',
    description: 'New car reviews, test drives, and automotive comparisons.',
    competitionLevel: 'high',
    monetizationPotential: 9,
    averageCPM: 20.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Doug DeMuro', url: 'https://youtube.com/@DougDeMuro', subscribers: '4.8M' },
      { name: 'Throttle House', url: 'https://youtube.com/@ThrottleHouse', subscribers: '2.2M' },
      { name: 'Straight Pipes', url: 'https://youtube.com/@TheStraightPipes', subscribers: '2.5M' },
    ],
    contentTypes: ['Review', 'Comparison', 'News', 'Test Drive'],
    targetAudience: 'Car enthusiasts and buyers aged 25-55',
    keywords: ['car review', 'automotive', 'cars', 'test drive', 'new cars'],
    requiresFace: true,
    minHoursPerWeek: 15,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
  {
    id: 'auto-diy',
    name: 'Auto DIY & Repair',
    category: 'automotive',
    description: 'Car repair tutorials, maintenance guides, and DIY automotive projects.',
    competitionLevel: 'medium',
    monetizationPotential: 8,
    averageCPM: 16.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'ChrisFix', url: 'https://youtube.com/@ChrisFix', subscribers: '11M' },
      { name: 'Scotty Kilmer', url: 'https://youtube.com/@ScottyKilmer', subscribers: '6M' },
      { name: 'Engineering Explained', url: 'https://youtube.com/@EngineeringExplained', subscribers: '3.5M' },
    ],
    contentTypes: ['Tutorial', 'DIY', 'Explanation', 'Review'],
    targetAudience: 'Car owners and DIY mechanics aged 20-50',
    keywords: ['car repair', 'auto DIY', 'maintenance', 'mechanic', 'how to'],
    requiresFace: true,
    minHoursPerWeek: 12,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },

  // FACELESS/LOW-COMPETITION NICHES
  {
    id: 'faceless-facts',
    name: 'Interesting Facts & Compilations',
    category: 'entertainment',
    description: 'Fascinating facts, list videos, and compilation content using stock footage.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 6.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Bright Side', url: 'https://youtube.com/@BRIGHTSIDE', subscribers: '45M' },
      { name: 'TheRichest', url: 'https://youtube.com/@TheRichest', subscribers: '17M' },
      { name: 'Facts Verse', url: 'https://youtube.com/@FactsVerse', subscribers: '8M' },
    ],
    contentTypes: ['List', 'Compilation', 'Facts', 'Explanation'],
    targetAudience: 'General audience aged 15-45',
    keywords: ['facts', 'interesting', 'compilation', 'list', 'did you know'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'faceless-motivation',
    name: 'Motivational & Quotes',
    category: 'lifestyle',
    description: 'Motivational speeches, quotes compilations, and inspirational content.',
    competitionLevel: 'high',
    monetizationPotential: 5,
    averageCPM: 5.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Motiversity', url: 'https://youtube.com/@Motiversity', subscribers: '5.5M' },
      { name: 'Mulligan Brothers', url: 'https://youtube.com/@MulliganBrothers', subscribers: '3.2M' },
      { name: 'MotivationHub', url: 'https://youtube.com/@MotivationHub', subscribers: '4M' },
    ],
    contentTypes: ['Compilation', 'Speech', 'Quotes', 'Story'],
    targetAudience: 'Self-improvement seekers aged 18-40',
    keywords: ['motivation', 'inspiration', 'success', 'quotes', 'mindset'],
    requiresFace: false,
    minHoursPerWeek: 6,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'faceless-asmr',
    name: 'ASMR',
    category: 'entertainment',
    description: 'ASMR content for relaxation, sleep, and stress relief.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 7.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'ASMR Darling', url: 'https://youtube.com/@ASMRDarling', subscribers: '2.6M' },
      { name: 'Gibi ASMR', url: 'https://youtube.com/@GibiASMR', subscribers: '4.5M' },
      { name: 'ASMR Zeitgeist', url: 'https://youtube.com/@ASMRZeitgeist', subscribers: '2.8M' },
    ],
    contentTypes: ['ASMR', 'Relaxation', 'Roleplay', 'Triggers'],
    targetAudience: 'Relaxation seekers and insomnia sufferers aged 16-40',
    keywords: ['ASMR', 'relaxation', 'sleep', 'tingles', 'calming'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'faceless-lofi',
    name: 'Lo-Fi Music & Study Beats',
    category: 'music',
    description: 'Background music for studying, working, and relaxation.',
    competitionLevel: 'medium',
    monetizationPotential: 4,
    averageCPM: 4.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Lofi Girl', url: 'https://youtube.com/@LofiGirl', subscribers: '14M' },
      { name: 'ChilledCow', url: 'https://youtube.com/@LofiGirl', subscribers: '14M' },
      { name: 'College Music', url: 'https://youtube.com/@CollegeMusic', subscribers: '3.5M' },
    ],
    contentTypes: ['Live Stream', 'Playlist', 'Mix', 'Background'],
    targetAudience: 'Students and remote workers aged 15-35',
    keywords: ['lofi', 'study music', 'chill beats', 'relaxing music', 'background music'],
    requiresFace: false,
    minHoursPerWeek: 4,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'faceless-storytime',
    name: 'Story Time & Narration',
    category: 'entertainment',
    description: 'Reddit stories, true crime narration, and storytelling content.',
    competitionLevel: 'medium',
    monetizationPotential: 6,
    averageCPM: 7.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Mr. Nightmare', url: 'https://youtube.com/@MrNightmare', subscribers: '7M' },
      { name: 'Lazy Masquerade', url: 'https://youtube.com/@LazyMasquerade', subscribers: '2.8M' },
      { name: 'Let\'s Read', url: 'https://youtube.com/@LetsRead', subscribers: '1.8M' },
    ],
    contentTypes: ['Narration', 'Story', 'Compilation', 'True Crime'],
    targetAudience: 'Story lovers and true crime fans aged 18-40',
    keywords: ['story time', 'reddit stories', 'true crime', 'narration', 'scary stories'],
    requiresFace: false,
    minHoursPerWeek: 8,
    bestForSkillLevel: ['beginner', 'intermediate'],
  },
  {
    id: 'faceless-explainer',
    name: 'Animated Explainers',
    category: 'education',
    description: 'Animated explanations of complex topics, how things work, and educational content.',
    competitionLevel: 'low',
    monetizationPotential: 7,
    averageCPM: 10.00,
    growthTrend: 'rising',
    exampleChannels: [
      { name: 'Kurzgesagt', url: 'https://youtube.com/@kurzgesagt', subscribers: '23M' },
      { name: 'TED-Ed', url: 'https://youtube.com/@TEDEd', subscribers: '19M' },
      { name: 'CGP Grey', url: 'https://youtube.com/@CGPGrey', subscribers: '6M' },
    ],
    contentTypes: ['Animation', 'Explanation', 'Education', 'Documentary'],
    targetAudience: 'Curious learners aged 14-50',
    keywords: ['animation', 'explainer', 'how it works', 'education', 'infographic'],
    requiresFace: false,
    minHoursPerWeek: 20,
    bestForSkillLevel: ['advanced'],
  },
  {
    id: 'faceless-cash-cow',
    name: 'Cash Cow Automation',
    category: 'entertainment',
    description: 'Highly scalable faceless content optimized for views and ad revenue.',
    competitionLevel: 'high',
    monetizationPotential: 7,
    averageCPM: 8.00,
    growthTrend: 'stable',
    exampleChannels: [
      { name: 'Chills', url: 'https://youtube.com/@Chills', subscribers: '8.5M' },
      { name: 'WatchMojo', url: 'https://youtube.com/@WatchMojo', subscribers: '25M' },
      { name: 'Screen Rant', url: 'https://youtube.com/@ScreenRant', subscribers: '10M' },
    ],
    contentTypes: ['List', 'Compilation', 'Ranking', 'News'],
    targetAudience: 'General entertainment audience aged 13-40',
    keywords: ['top 10', 'list', 'facts', 'compilation', 'ranking'],
    requiresFace: false,
    minHoursPerWeek: 10,
    bestForSkillLevel: ['intermediate', 'advanced'],
  },
];

// Helper functions
export function getNicheById(id: string): NicheData | undefined {
  return NICHE_DATABASE.find(niche => niche.id === id);
}

export function getNichesByCategory(category: string): NicheData[] {
  return NICHE_DATABASE.filter(niche => niche.category === category);
}

export function getFacelessNiches(): NicheData[] {
  return NICHE_DATABASE.filter(niche => !niche.requiresFace);
}

export function getLowCompetitionNiches(): NicheData[] {
  return NICHE_DATABASE.filter(niche => niche.competitionLevel === 'low');
}

export function getHighMonetizationNiches(minScore: number = 8): NicheData[] {
  return NICHE_DATABASE.filter(niche => niche.monetizationPotential >= minScore);
}

export function getRisingNiches(): NicheData[] {
  return NICHE_DATABASE.filter(niche => niche.growthTrend === 'rising');
}

export function getBeginnerFriendlyNiches(): NicheData[] {
  return NICHE_DATABASE.filter(niche => niche.bestForSkillLevel.includes('beginner'));
}

export function searchNiches(query: string): NicheData[] {
  const lowercaseQuery = query.toLowerCase();
  return NICHE_DATABASE.filter(niche =>
    niche.name.toLowerCase().includes(lowercaseQuery) ||
    niche.description.toLowerCase().includes(lowercaseQuery) ||
    niche.keywords.some(keyword => keyword.toLowerCase().includes(lowercaseQuery))
  );
}
