import { logger } from "@/lib/logger";
import { prisma } from "@/lib/prisma";

export interface AgentContext {
  jobId: string;
  projectId: string;
  clipId?: string;
  userId: string;
  config: Record<string, any>;
  transcript?: string;
  clipStartMs?: number;
  clipEndMs?: number;
  assetPath?: string;
  previousResults?: Record<string, any>;
}

export interface AgentResult {
  success: boolean;
  data?: Record<string, any>;
  error?: string;
  assets?: Array<{
    type: string;
    source: string;
    path: string;
    metadata?: Record<string, any>;
    startMs?: number;
    endMs?: number;
  }>;
}

export abstract class BaseAgent {
  protected name: string;

  constructor(name: string) {
    this.name = name;
  }

  /**
   * Main execution method that each agent must implement
   */
  abstract execute(context: AgentContext): Promise<AgentResult>;

  /**
   * Log the start of agent execution
   */
  protected async logStart(context: AgentContext): Promise<string> {
    const log = await prisma.agentExecutionLog.create({
      data: {
        jobId: context.jobId,
        agentName: this.name,
        status: "started",
        input: {
          config: context.config,
          clipId: context.clipId,
          projectId: context.projectId
        }
      }
    });

    logger.info(`Agent ${this.name} started`, {
      jobId: context.jobId,
      logId: log.id
    });

    return log.id;
  }

  /**
   * Log the completion of agent execution
   */
  protected async logComplete(
    logId: string,
    result: AgentResult,
    durationMs: number
  ): Promise<void> {
    await prisma.agentExecutionLog.update({
      where: { id: logId },
      data: {
        status: result.success ? "completed" : "failed",
        output: result.data,
        error: result.error,
        durationMs
      }
    });

    logger.info(`Agent ${this.name} completed`, {
      logId,
      success: result.success,
      durationMs
    });
  }

  /**
   * Save assets generated by this agent
   */
  protected async saveAssets(
    context: AgentContext,
    assets: AgentResult["assets"]
  ): Promise<void> {
    if (!assets || assets.length === 0) {
      return;
    }

    await prisma.agentAsset.createMany({
      data: assets.map((asset) => ({
        jobId: context.jobId,
        type: asset.type,
        source: asset.source,
        path: asset.path,
        metadata: asset.metadata || {},
        startMs: asset.startMs,
        endMs: asset.endMs
      }))
    });

    logger.info(`Agent ${this.name} saved ${assets.length} assets`, {
      jobId: context.jobId
    });
  }

  /**
   * Update job progress
   */
  protected async updateProgress(
    jobId: string,
    progress: Record<string, any>
  ): Promise<void> {
    await prisma.agentEditorJob.update({
      where: { id: jobId },
      data: {
        currentAgent: this.name,
        progress
      }
    });
  }

  /**
   * Run the agent with logging and error handling
   */
  async run(context: AgentContext): Promise<AgentResult> {
    const startTime = Date.now();
    const logId = await this.logStart(context);

    try {
      await this.updateProgress(context.jobId, {
        currentAgent: this.name,
        status: "processing"
      });

      const result = await this.execute(context);

      if (result.success && result.assets) {
        await this.saveAssets(context, result.assets);
      }

      const durationMs = Date.now() - startTime;
      await this.logComplete(logId, result, durationMs);

      return result;
    } catch (error) {
      const durationMs = Date.now() - startTime;
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";

      const result: AgentResult = {
        success: false,
        error: errorMessage
      };

      await this.logComplete(logId, result, durationMs);

      logger.error(`Agent ${this.name} failed`, {
        jobId: context.jobId,
        error: errorMessage
      });

      return result;
    }
  }
}
